### ISSUE TITLE
Development of the .characteristic_poly method for ODESystem

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#108]
A novel approach for computing the characteristic polynomial is required, which can be integrated into the ODESystem as one of its features. This approach must have the capability to efficiently generate the characteristic polynomial for Ordinary Differential Equations (ODEs). It should be adaptable for systems with multiple degrees of freedom by leveraging matrix computations.

**Comment by grzegorzdl** [comment]
Method implemented successfully. I am closing the issue
