### ISSUE TITLE
Development of `PhysicalPendulum` dynamic system

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#112]
New system is to implement is module `pendulum.py`. It should be inherited from similar class being implemented within scope of the module if possible.

**Comment by Fyla** [comment]
Class has been implemented.
No valid schemes (21.08.2024 - planned addition).

**Comment by Fyla** [comment]
The code was checked with the following call:

```
from dynpy.models.mechanics import CompoundPendulum
from dynpy.utilities.documents.document import DynSysOverviewReport
DynSysOverviewReport(reported_object=CompoundPendulum())
```
