### ISSUE TITLE
Development of ForcedDisksWithParallelSprings and ForcedDisksWithParallelSprings2 dynamic systems

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#114]
The systems require reimplementation ( improvement of __innit__ method and implementation of components method)

**Comment by Woojaszek2137** [comment]
System ForcedDisksWithParallelSprings has been reimplemented and can be found in disks.py module.
System ForcedDisksWithParallelSprings2 was a copy of the system from above and was removed.

Issue can be closed.
