### ISSUE TITLE
Exemplary descriptions of Github commit and list of possible comments (flags)

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#124]
There is a need to suppement the guide from the [issue](https://github.com/bogumilchilinski/dynpy/issues/15) with the copyable comments for Commits.

**Comment by augsav** [comment]
Code snippets added. Also the document form has been updated to the template one. The guide can be found in the [file](https://github.com/bogumilchilinski/dynpy/files/12457788/Guide.on.Github.synchronization.Cocalc.version.pdf).
