### ISSUE TITLE
Implementation of ._calculate_constant method

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#13]
Separate method for constant obtaining is needed. The method should be added in [ODESolution](https://github.com/bogumilchilinski/dynpy/blob/7ad2b05651e0a2a2efd47cad76383882e670c57c/solvers/linear.py#L539) and it has to be able to calculate the values of integration constants with dictionary of ics values.
The prototype of *_calculate_constant* method is coded in:

https://github.com/bogumilchilinski/dynpy/blob/7ad2b05651e0a2a2efd47cad76383882e670c57c/solvers/linear.py#L649-L660

**Comment by bogumilchilinski** [comment]
Franek ( @fgawinski ),

  Is it finished? You fixed it as I remember?

**Comment by fgawinski** [comment]
Using dvars_str argument with with_ics parameter solves this problem partialy, but it should be done better.

I am leaving this issue in progress status

**Comment by fgawinski** [comment]
I created new function _get_dvars_str that is used in with_ics. You can used with_ics without any parameters given.

I am changing status to 'in progress'.

**Comment by fgawinski** [comment]
There is no bugs in with_ics noticed. Additionally you can use it without any parameters.

I ma closing this issue.
