### ISSUE TITLE
Presentation for 2023 WUT-TUB scientific meeting

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#147]
Edit and enhance the presentation for 2023 WUT-TUB conference

**Comment by amvdek** [comment]
Beamer jupyter - https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Jakub%20Szyd%C5%82owski/latexBeamer/beamer_temp_ULTRA.ipynb

Output PDF file of beamer - https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Jakub%20Szyd%C5%82owski/latexBeamer/output/prezka_done.pdf
