### ISSUE TITLE
Review of guide for synchronization of git repositories

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#15]
Review the guidelines for synchronization of git repos. The report code can be found in [the notebook](https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Saveena%20Augustyniak/Guide/git%20sync%20guide.ipynb) in Ongoing Projects.

**Comment by mopar4or2no6car** [comment]
NAJWAŻNIEJSZE:
Na początku należy określić, że są dwie opcje - albo Commit się pojawia w panelu po lewej, albo nie. W pierwszej kolejności należy opisać co zrobić, gdy go nie ma (przenieść treść zaczynającą się od zdania "Jeśli commit nie działa"). Dopiero potem informacje o sposobie postępowania, gdy Commit jest dostępny. 
 
Poza tym:
- rozdzielić treść od strony tytułowej,
- zamiast jednego rozdziału "Krok po kroku" rozpisać poszczególne czynności na rozdziały jako "Krok 1", "Krok 2", itd.
- dodać podpisy pod zdjęciami,
- spacje przed myślnikami w tekstach "abd - def",
- cudzysłowy zamiast apostrofów - "Commit",
- ogólna stylistyka.

**Comment by augsav** [comment]
The corrected report code is now in [notebook](https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Sav/Guide%20come%20back/git%20sync%20guide.ipynb). Separate front page is now a different issue and will be corrected in the future.
[Guide on Github synchronization (Cocalc version).pdf](https://github.com/bogumilchilinski/dynpy/files/12412708/Guide.on.Github.synchronization.Cocalc.version.pdf)
