### ISSUE TITLE
Development of TripleShaft dynamic systems

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#158]
New system is to implement is module `shaft.py`. It should be inherited from similar class being implemented within scope of the module if possible.

**Comment by Fyla** [comment]
The code was checked with the following call:

```
from dynpy.models.mechanics.shaft import TripleShaft
from dynpy.utilities.documents.document import DynSysOverviewReport


DynSysOverviewReport(reported_object=TripleShaft())
```
