### ISSUE TITLE
Maintenance of mechanics (`mechanics.__init__.py`) DynPy module

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#16]
Prepare few exemplary mechanical system as an example of proper code implementation in module [mechanics](https://github.com/bogumilchilinski/dynpy/blob/ee555b58f7f6efa5d849073329388bac248c5806/models/mechanics/). Check it with `DynSysOverviewReport` class which generates calculations for system under investigation and propose some validation algorithm.

There is a need to relocate systems being listed:

- [x] #46
- [x] #47
- [x] #48
- [x] #78
- [x] #79

List of systems to improve:

- [x] #41

- [x] #59

- [x] #60

- [x] #113

- [x] #114

- [x] #115

- [x] #84 

- [x] #85

- [x] #86

- [x] #112

- [x] #54

- [x] #55

- [x] #56

- [x] #62

- [x] #37
 
- [x] #38

- [x] #39

- [x] #57

- [x] #58

- [x] #40

- [x] #43

- [x] #42

- [x] #51

**Comment by bogumilchilinski** [comment]
@amvdek could you list the projects which were assigned to particular person?

**Comment by amvdek** [comment]
(Additional cases?)
@kubapodgorzak, @Daniel_Stryjewski, @Mk11-10, @Sabina_Sypniewska

**Comment by amvdek** [comment]
Additional cases:

ddof.py
   Inverted_Pendulum
   TwoDisksWithThreeSprings
   VeeEnginePerpendicularSprings
   QuarterOfVehicle

mdof.py
   DDoFWinch
   DampedElasticPendulum
   ThreePendulumsWithSprings
   MDoFForcedSimpleDisksWithParallelSprings
   MDoFForcedSimpleDisksWithSerialSprings
   DoublePendulum
   LinearizedTriplePendulum
   
systems.py
   SDOFDrivetrainVehicleSystem
   LagrangeIBlocksOnInclinedPlane
   SDOFWinchSystem

**Comment by bogumilchilinski** [comment]
All done.
