### ISSUE TITLE
Improvement of the paper about Trolley with Pendulum model with varying mass (if needed) after reviewers information

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#175]
Improve the form of the paper after reviewer suggestions. Reupload improved files into editorial system.

- [x] #235

- [x] #236

- [x] #237

- [x] #238

**Comment by amvdek** [comment]
Paper is improved and was sent to editors. On 18.11.23 paper was sent to reviewers by editors.

**Comment by amvdek** [comment]
Paper accepted by the reviewers
