### ISSUE TITLE
Development of reporting components (ReportComponent class) for DynamicSystem class

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#19]
List of new reporting classes for DynPy's code and SymPy's code.

### List of classes to implementation

- [x] #27 

- [x] #28

- [x] #25

- [x] #30 

- [x] #26 
 
- [x] #31 
 
- [x] #32
 
- [x] #33

**Comment by amvdek** [comment]
Example of report component with code is in this jupyter:
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Krzysztof%20Kaczmarzyk/ReportTools.ipynb#id=7c81f2

**Comment by amvdek** [comment]
SchemeComponent
ExemplaryPictureComponent
KineticEnergyComponent
PotentialEnergyComponent
LagrangianComponent
GoverningEquationComponent
FundamentalMatrixComponent
GeneralSolutionComponent

**Comment by amvdek** [comment]
(Additional cases?)
@kubapodgorzak, @Daniel_Stryjewski, @Mk11-10, @Sabina_Sypniewska

**Comment by amvdek** [comment]
Additional cases:

DissipationSymPyCodeComponent
DissipationDynPyCodeComponent

LinearizedGoverningEquationSymPyCodeComponent
LinearizedGoverningEquationDynPyCodeComponent

LinearizationSymPyCodeComponent
LinearizationDynPyCodeComponent

FrequencyResponseFunctionSymPyCodeComponent
FrequencyResponseFunctionDynPyCodeComponent

SpringForceSymPyCodeComponent
SpringForceDynPyCodeComponent

DamperForceSymPyCodeComponent
DamperForceDynPyCodeComponent

LogarithmicDecrementSymPyCodeComponent
LogarithmicDecrementDynPyCodeComponent

SteadySolutionSymPyCodeComponent
SteadySolutionDynPyCodeComponent

StaticForceSymPyCodeComponent
StaticForceDynPyCodeComponent

DynamicForceSymPyCodeComponent
DynamicForceDynPyCodeComponent

**Comment by KrzysztofKaczmarzyk** [comment]
All of the points have been achieved. Issue can be closed
