### ISSUE TITLE
Preparation of meeting and guide for implementation of ReportingComponets

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#20]
The following actions are to do, in order to prepare the meeting and the guide:

- [x] #273

- [x] #274

- [x] #275

**Comment by amvdek** [comment]
Example of component with code is in this jupyter:
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Krzysztof%20Kaczmarzyk/ReportTools.ipynb#id=7c81f2

**Comment by Woojaszek2137** [comment]
@KrzysztofKaczmarzyk @kjaskiel @Mk11-10 
Guys, place the finał version of the guide in the issue #29, Please.

**Comment by KrzysztofKaczmarzyk** [comment]
Issue can be closed. Report Code and generated pdf file can be found here: 
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Krzysztof%20Kaczmarzyk/

**Comment by KrzysztofKaczmarzyk** [comment]
All of the points are achieved. Issue can be closed
