### ISSUE TITLE
Development of `MDoFDampedTrolleysWithSprings` dynamic systems

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#209]
New system is to implement is module `trolleys.py`. It should be inherited from similar class being implemented within scope of the module if possible.

**Comment by MichalKacperek** [comment]
Dynamic system MDoFDampedTrolleysWithSprings is same as DampedTrolleysWithSprings. Class MDoFDampedTrolleysWithSprings has been removed. #205
