### ISSUE TITLE
Preparation of meeting and instruction with introduction to DynPy module structure

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#21]
The following actions are to do, in order to prepare the meeting and the guide:

- [x] #257

- [x] #258

- [x] #259

**Comment by kziabrowska** [comment]
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/Application%20examples/%5BTemplate%5D%20Guide/output/guide_1.pdf

**Comment by Woojaszek2137** [comment]
@kziabrowska send me  the final version of the guide for the issue #29, Please.

**Comment by bogumilchilinski** [comment]
Document is finished. It provides basic information about DynPy structure.

**Comment by amvdek** [comment]
#259 is the last subissue needed to close this issue. Let’s end it ASAP

**Comment by amvdek** [comment]
Everything's done
