### ISSUE TITLE
Development of `SDoFDoubleTrolleyDifferentWheels` dynamic systems

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#210]
New system is to implement in module `trolleys.py`. It should be inherited from similar class being implemented within scope of the module if possible.

**Comment by MichalKacperek** [comment]
Dynamic system SDoFDoubleTrolleyDifferentWheels is same as DoubleTrolleyDifferentWheels. Class SDoFDoubleTrolleyDifferentWheels has been removed. #206
