### ISSUE TITLE
Development of MDoFForcedTrolleysWithSprings dynamic systems

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#211]
New system is to implement is module `trolleys.py`. It should be inherited from similar class being implemented within scope of the module if possible.

**Comment by MichalKacperek** [comment]
Methods `get_numerical_data`, `symbols_description`, `unit_dict` have been added.

**Comment by MichalKacperek** [comment]
`MDoFForcedTrolleysWithSprings` class is same as `ForcedTrolleysWithSprings` #207. `MDoFForcedTrolleysWithSprings` has been changed to `ForcedTrolleysWithSprings`.

The code was checked with the following call:
```
from dynpy.models.mechanics.trolleys import ForcedTrolleysWithSprings
from dynpy.utilities.documents.document import DynSysOverviewReport
DynSysOverviewReport(reported_object=ForcedTrolleysWithSprings())
```
