### ISSUE TITLE
Development of `MDoFTMD` dynamic systems

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#212]
New system is to implement is module `trolleys.py`. It should be inherited from similar class being implemented within scope of the module if possible.

**Comment by Piotr-Loch** [comment]
The `MDoFTMD` class has been implemented. The code was checked with the following call:

```python
from dynpy.models.mechanics import MDoFTMD
from dynpy.utilities.documents.document import DynSysOverviewReport
DynSysOverviewReport(reported_object=MDoFTMD());
```
