### ISSUE TITLE
Template for solution of a mechanical problem

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#22]
There is a need of template (exemplary solution) of selected case as example of solving and reporting method.

**Comment by grzegorzdl** [comment]
Link to template - https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/Application%20examples/%5BTemplate%5D%20Mechanical%20case/guide_mechana.ipynb
