### ISSUE TITLE
Arrangement of an thesis on a concept of environment for automatically generated engineering reports

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#220]
Scope of the thesis is as follows:

- [x] Diploma thesis card fullfilment

- [x] Gathering all guides

- [x] Phrasing of the subject of thesis

- [x] Extended perspective on implementation of the modules in dynpy

- [x] Validation of the simulation outcomes

- [x] Proposal of possible applications

- [x] Writing the thesis, introduction, dynpy class structure , examples of dynamic systems, possible applications

- [x] Thesis review

- [x] Thesis improvement

- [x] Final approval of the thesis

**Comment by Woojaszek2137** [comment]
The Thesis has been submited. Issue can be closed
