### ISSUE TITLE
Correct linguistic errors, typos, scheme (issue #175 related)

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#235]
Correct the mistakes marked by reviewers. Generalized coordinates, typos, linguistic errors.

**Comment by amvdek** [comment]
Mistakes corrected using grammarly, generalized coordinates are now changed on the scheme. Text enhanced thaks to @mopar4or2no6car 's and @bogumilchilinski 's critical revision.
