### ISSUE TITLE
Template class for guidelines of Engineering Drawing project

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#24]
Create (by coping) new class for guidelines template. Copy MechanicalCase or DevelopmentGuide class from document.py.

**Comment by Woojaszek2137** [comment]
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/Marek%20Skwarka/Shared%20files/modules/dynpy/utilities/templates/document.py

**Comment by bogumilchilinski** [comment]
Everything seems to be okay. Close as finished.
