### ISSUE TITLE
Implementation of KineticEnergyDynPyCodeComponent and KineticEnergySymPyCodeComponent classes

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#25]
Two classes for code reporting are to create. KineticEnergyDynPyCodeComponent and KineticEnergySymPyCodeComponent have to embed an examples of DynPy or/and SymPy classes and methods application which present kinetic energy calculations.

**Comment by KrzysztofKaczmarzyk** [comment]
Imports and printing automations required to do. Link to the jupyter notebook below. 

https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Krzysztof%20Kaczmarzyk/ReportTools.ipynb#id=4c7349

**Comment by KrzysztofKaczmarzyk** [comment]
https://github.com/bogumilchilinski/dynpy/blob/dc2c43860a0e45de3fdac0fae53d6e61abbc0d93/utilities/components/mech/en.py#L274 L355

**Comment by bogumilchilinski** [comment]
Closed as finished.
