### ISSUE TITLE
Implementation of LagrangianDynPyCodeComponent and LagrangianSymPyCodeComponent classes

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#26]
Two classes for code reporting are to create. LagrangianDynPyCodeComponent and LagrangianSymPyCodeComponent have to embed an examples of DynPy or/and SymPy classes and methods application which present lagrangian calculations.

**Comment by amvdek** [comment]
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/Marek%20Skwarka/Shared%20files/modules/dynpy/utilities/components/mech/en.py#line=741
