### ISSUE TITLE
Implementation of ExemplaryPictureDynPyCodeComponent and ExemplaryPictureSymPyCodeComponent classes

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#28]
Two classes for code reporting are to create. Mentioned classes have to embed an examples of DynPy or/and SymPy classes and methods application which present picture of exemplary real object.

**Comment by amvdek** [comment]
ExemplaryPictureDynPyCodeComponent

https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/Marek%20Skwarka/Shared%20files/modules/dynpy/utilities/components/mech/en.py#line=105

**Comment by bogumilchilinski** [comment]
Everything seems to be okay.

**Comment by amvdek** [comment]
ExemplaryPictureSympyCodeComponent

https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/Marek%20Skwarka/Shared%20files/modules/dynpy/utilities/components/mech/en.py#line=143
