### ISSUE TITLE
Relocation of guides and reports from internship meetings

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#29]
Relocation of all guides and reports which are started is needed to common space in order to finish with development of these. @amvdek, @kziabrowska, @kjaskiel , @banasiakm , @Woojaszek2137 , could you create **work in progress** folder on www.cocalc.com and move all the guides there? Let's post a link here, when you move particular file to the folder.

- [x] #44 

- [x] #75 

- [x] #21

- [x] #20 

- [x] #34 

- [x] #52

- [x] #53

- [x] #15

**Comment by kziabrowska** [comment]
here you can move your files: https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/%5BWIP%5D%20Guidelines%20-%20Work%20In%20Progress/

**Comment by Woojaszek2137** [comment]
Guide #44 can be found in this PDF file: 
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Jakub%20Szydłowski/Output/GuideCoCalc.pdf
