### ISSUE TITLE
Implementation of PotentialEnergyDynPyCodeComponent and PotentialEnergySymPyCodeComponent classes

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#30]
Two classes for code reporting are to create. Mentioned classes have to embed an examples of DynPy or/and SymPy classes and methods application which present potential energy calculations.

**Comment by amvdek** [comment]
SymPy - https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/Marek%20Skwarka/Shared%20files/modules/dynpy/utilities/components/mech/en.py#line=392

DynPy - https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/Marek%20Skwarka/Shared%20files/modules/dynpy/utilities/components/mech/en.py#line=353

**Comment by KrzysztofKaczmarzyk** [comment]
Done. Issue can be closed.
