### ISSUE TITLE
Implementation of class for Gear Meshing model that represents dynamic system (issue #142 related)

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#305]
System is to implement or improve in module `gear.py`. It should be inherited from similar class being implemented within scope of the module if possible.

**Comment by bugkarol** [comment]
Class was checked by the following call:

```python
from dynpy.models.mechanics.gears import DDOFGearMechanism
DDOFGearMechanism(None);
```
