### ISSUE TITLE
Analysis of state of the art regarding tooth stiffness (issue #306 related)

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#308]
The goal is to locate an adequate number of articles and craft a state-of-the-art assessment based on their contents.

**Comment by KrzysztofKaczmarzyk** [comment]
https://cocalc.com/projects/f5eacfa1-ad37-41af-beea-da7216cf5881/files/%5BPaper%5D%5BWIP%5D%20Gear/paper.ipynb#id=c69da9

**Comment by KrzysztofKaczmarzyk** [comment]
Issue can be closed
