### ISSUE TITLE
Analysis of state of the art regarding parametric vibration of gear (rattling) (issue #306 related)

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#309]

**Comment by Eratostenes** [comment]
**Done**

Numerical and experimental study of gear rattle based on a refined dynamic model
Applied Acoustics, Volume 185, 1 January 2022, 108407
DOI: https://doi.org/10.1016/j.apacoust.2021.108407

Investigation of gear rattle noise including visualization of vibro-impact regimes 
–––––> ”prawie” KLASYK <–––––
Journal of Sound and Vibration , Volume 467, 17 February 2020, 115026
DOI: https://doi.org/10.1016/j.jsv.2019.115026

Experimental and numerical analysis of automotive gearbox rattle noise 
–––––> ”prawie” KLASYK <–––––
Journal of Sound and Vibration , Volume 331, Issue 13, 18 June 2012, Pages 3144-3157
DOI: https://doi.org/10.1016/j.jsv.2012.02.009

Analysis of automotive neutral grear rattle 
–––––> tzw. KLASYK <–––––
Journal of Sound and Vibration, Volume 131, Issue 2, 8 June 1989, Pages 177-196
DOI: https://doi.org/10.1016/0022-460X(89)90485-9

Evaluation of root stresses of a rattling gear pair
Mechanical Systems and Signal Processing, Volume 196, 1 August 2023, 110335
DOI: https://doi.org/10.1016/j.ymssp.2023.110335

Experimental investigation of gear rattle and nonlinear dynamic interaction in a dual-clutch transmission
Applied Acoustics, Volume 204, 15 March 2023, 109233
DOI: https://doi.org/10.1016/j.apacoust.2023.109233

Modeling and analysis of friction clutches with three stages stiffness and damping for reducing gear rattles of unloaded gears at transmission
Journal of Sound and Vibration, Volume 483, 29 September 2020, 115469
DOI: https://doi.org/10.1016/j.jsv.2020.115469

Optimization on nonlinear dynamics of gear rattle in automotive transmission system
Shock and Vibration, Volume 2019, 24 December 2019, 4056204
DOI: https://doi.org/10.1155/2019/4056204

Torsional vibration model based optimization of gearbox geometric design parameters to reduce rattle noise in an automotive transmission
Mechanism and Machine Theory, Volume 45, Issue 11, November 2010, Pages 1583-1598
DOI: https://doi.org/10.1016/j.mechmachtheory.2010.06.014

The transmission gear rattle noise: parametric sensitivity study
SAE 2004 World Congress & Exhibition 
March 08, 2004 by SAE International in United States 
2004-01-1225 ISSN: 0148-7191, e-ISSN: 2688-3627
DOI: https://doi.org/10.4271/2004-01-1225

Gear Rattling Noises from Vehicle Transmissions
https://link.springer.com/chapter/10.1007/978-3-658-37708-3_3
21 July 2022
W: Minimizing of Automotive Transmission Rattle Noise by Means of Gear Oils , Springer, 2023, pp 21–33

**Comment by Eratostenes** [comment]
The task was to search for and select scientific publications on parametric vibration of gears in the context of rattling issues.

**A list of selected papers below :**

Numerical and experimental study of gear rattle based on a refined dynamic model
Applied Acoustics, Volume 185, 1 January 2022, 108407
DOI: https://doi.org/10.1016/j.apacoust.2021.108407

Investigation of gear rattle noise including visualization of vibro-impact regimes 
–––––> ”prawie” KLASYK <–––––
Journal of Sound and Vibration , Volume 467, 17 February 2020, 115026
DOI: https://doi.org/10.1016/j.jsv.2019.115026

Experimental and numerical analysis of automotive gearbox rattle noise 
–––––> ”prawie” KLASYK <–––––
Journal of Sound and Vibration , Volume 331, Issue 13, 18 June 2012, Pages 3144-3157
DOI: https://doi.org/10.1016/j.jsv.2012.02.009

Analysis of automotive neutral grear rattle 
–––––> tzw. KLASYK <–––––
Journal of Sound and Vibration, Volume 131, Issue 2, 8 June 1989, Pages 177-196
DOI: https://doi.org/10.1016/0022-460X(89)90485-9

Parametric modelling of vibration response for high-speed gear transmission system
International Journal of Mechanical Sciences, Volume 249, 1 July 2023, 108273
DOI: https://doi.org/10.1016/j.ijmecsci.2023.108273

Evaluation of root stresses of a rattling gear pair
Mechanical Systems and Signal Processing, Volume 196, 1 August 2023, 110335
DOI: https://doi.org/10.1016/j.ymssp.2023.110335

Experimental investigation of gear rattle and nonlinear dynamic interaction in a dual-clutch transmission
Applied Acoustics, Volume 204, 15 March 2023, 109233
DOI: https://doi.org/10.1016/j.apacoust.2023.109233

Modeling and analysis of friction clutches with three stages stiffness and damping for reducing gear rattles of unloaded gears at transmission
Journal of Sound and Vibration, Volume 483, 29 September 2020, 115469
DOI: https://doi.org/10.1016/j.jsv.2020.115469

Optimization on nonlinear dynamics of gear rattle in automotive transmission system
Shock and Vibration, Volume 2019, 24 December 2019, 4056204
DOI: https://doi.org/10.1155/2019/4056204

A rattle index formulation for single and multiple branch geartrains
Mechanism and Machine Theory, Volume 158, April 2021, 104246
https://doi.org/10.1016/j.mechmachtheory.2021.104246

Empirical model based optimization of gearbox geometric design parameters to reduce rattle noise in an automotive transmission
Mechanism and Machine Theory, Volume 45, Issue 11, November 2010, Pages 1599-1612
DOI: https://doi.org/10.1016/j.mechmachtheory.2010.06.013

Torsional vibration model based optimization of gearbox geometric design parameters to reduce rattle noise in an automotive transmission
Mechanism and Machine Theory, Volume 45, Issue 11, November 2010, Pages 1583-1598
DOI: https://doi.org/10.1016/j.mechmachtheory.2010.06.014

No-linear dynamics of gear-pair systems with periodic stiffness and backlash
Journal of Sound and Vibration, Volume 229, Issue 2, 13 January 2000, Pages 287-310
DOI: https://doi.org/10.1006/jsvi.1999.2490

The transmission gear rattle noise: parametric sensitivity study
SAE 2004 World Congress & Exhibition 
March 08, 2004 by SAE International in United States 
2004-01-1225 ISSN: 0148-7191, e-ISSN: 2688-3627
DOI: https://doi.org/10.4271/2004-01-1225

Gear Rattling Noises from Vehicle Transmissions
https://link.springer.com/chapter/10.1007/978-3-658-37708-3_3
21 July 2022
W: Minimizing of Automotive Transmission Rattle Noise by Means of Gear Oils , Springer, 2023, pp 21–33

**Comment by Eratostenes** [comment]
The task was to search for and select scientific publications on parametric vibration of gears in the context of rattling issues.

**A list of selected articles is below:**

Numerical and experimental study of gear rattle based on a refined dynamic model
Applied Acoustics, Volume 185, 1 January 2022, 108407
DOI: https://doi.org/10.1016/j.apacoust.2021.108407

Investigation of gear rattle noise including visualization of vibro-impact regimes 
–––––> ”prawie” KLASYK <–––––
Journal of Sound and Vibration , Volume 467, 17 February 2020, 115026
DOI: https://doi.org/10.1016/j.jsv.2019.115026

Experimental and numerical analysis of automotive gearbox rattle noise 
–––––> ”prawie” KLASYK <–––––
Journal of Sound and Vibration , Volume 331, Issue 13, 18 June 2012, Pages 3144-3157
DOI: https://doi.org/10.1016/j.jsv.2012.02.009

Analysis of automotive neutral grear rattle 
–––––> tzw. KLASYK <–––––
Journal of Sound and Vibration, Volume 131, Issue 2, 8 June 1989, Pages 177-196
DOI: https://doi.org/10.1016/0022-460X(89)90485-9

Parametric modelling of vibration response for high-speed gear transmission system
International Journal of Mechanical Sciences, Volume 249, 1 July 2023, 108273
DOI: https://doi.org/10.1016/j.ijmecsci.2023.108273

Evaluation of root stresses of a rattling gear pair
Mechanical Systems and Signal Processing, Volume 196, 1 August 2023, 110335
DOI: https://doi.org/10.1016/j.ymssp.2023.110335

Experimental investigation of gear rattle and nonlinear dynamic interaction in a dual-clutch transmission
Applied Acoustics, Volume 204, 15 March 2023, 109233
DOI: https://doi.org/10.1016/j.apacoust.2023.109233

Modeling and analysis of friction clutches with three stages stiffness and damping for reducing gear rattles of unloaded gears at transmission
Journal of Sound and Vibration, Volume 483, 29 September 2020, 115469
DOI: https://doi.org/10.1016/j.jsv.2020.115469

Optimization on nonlinear dynamics of gear rattle in automotive transmission system
Shock and Vibration, Volume 2019, 24 December 2019, 4056204
DOI: https://doi.org/10.1155/2019/4056204

A rattle index formulation for single and multiple branch geartrains
Mechanism and Machine Theory, Volume 158, April 2021, 104246
https://doi.org/10.1016/j.mechmachtheory.2021.104246

Empirical model based optimization of gearbox geometric design parameters to reduce rattle noise in an automotive transmission
Mechanism and Machine Theory, Volume 45, Issue 11, November 2010, Pages 1599-1612
DOI: https://doi.org/10.1016/j.mechmachtheory.2010.06.013

Torsional vibration model based optimization of gearbox geometric design parameters to reduce rattle noise in an automotive transmission
Mechanism and Machine Theory, Volume 45, Issue 11, November 2010, Pages 1583-1598
DOI: https://doi.org/10.1016/j.mechmachtheory.2010.06.014

No-linear dynamics of gear-pair systems with periodic stiffness and backlash
Journal of Sound and Vibration, Volume 229, Issue 2, 13 January 2000, Pages 287-310
DOI: https://doi.org/10.1006/jsvi.1999.2490

The transmission gear rattle noise: parametric sensitivity study
SAE 2004 World Congress & Exhibition 
March 08, 2004 by SAE International in United States 
2004-01-1225 ISSN: 0148-7191, e-ISSN: 2688-3627
DOI: https://doi.org/10.4271/2004-01-1225

Gear Rattling Noises from Vehicle Transmissions
https://link.springer.com/chapter/10.1007/978-3-658-37708-3_3
21 July 2022
W: Minimizing of Automotive Transmission Rattle Noise by Means of Gear Oils , Springer, 2023, pp 21–33
