### ISSUE TITLE
Analysis of state of the art regarding analytical methods for parametric vibration (issue #306 related)

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#310]
The aim was to find articles regarding analytical methods for parametric vibration

**Comment by KrzysztofKaczmarzyk** [comment]
https://cocalc.com/projects/f5eacfa1-ad37-41af-beea-da7216cf5881/files/%5BPaper%5D%5BWIP%5D%20Gear/paper.ipynb#id=c69da9
