### ISSUE TITLE
Implementation of FundamentalMatrixDynPyCodeComponent and FundamentalMatrixSymPyCodeComponent classes

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#32]
Two classes for code reporting are to create. Mentioned classes have to embed an examples of DynPy or/and SymPy classes and methods application which present fundamental matrix calculations.

**Comment by Woojaszek2137** [comment]
Code for this component is in this link:
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Jakub%20Szydłowski/FundamentalMatrixComponent.ipynb#id=3bf212

**Comment by grzegorzdl** [comment]
Both classes developed. Issue closed as finished
