### ISSUE TITLE
Preparation of meeting and guide for presentation of latest development achievements in modules: reporting and solvers

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#326]
The following actions are to do, in order to prepare the meeting and the guide:

- [x] #327 

- [x] #328

- [ ] #329

**Comment by Piotr-Loch** [comment]
The following guide is to improve: https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/%5BWIP%5D%20Guidelines/%5BPL%5D%5BGuide%5D%5BDevelopment%5D%20Śledzenie%20podstępów%20prac.pdf
