### ISSUE TITLE
Implementation of GeneralSolutionDynPyCodeComponent and GeneralSolutionSymPyCodeComponent classes

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#33]
Two classes for code reporting are to create. Mentioned classes have to embed an examples of DynPy or/and SymPy classes and methods application which present general solution calculations for a differential equation being related to a dynamic system.

**Comment by KrzysztofKaczmarzyk** [comment]
Component has been implemented and gives acceptable output. Issue can be closed.
