### ISSUE TITLE
Development of the template or document class for WUT Thesis

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#334]
The goal is to enhance or refactor a class that implements a document class (from reporting module) with properties matched with WUT theses requirements.

**Comment by amvdek** [comment]
Template WutThesis is done

https://cocalc.com/projects/f5eacfa1-ad37-41af-beea-da7216cf5881/files/Shared%20files/modules/dynpy/utilities/templates/document.py#line=209
