### ISSUE TITLE
Implementation of SolutionComponent class that reports solution

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#339]
The goal is to generate and explain the solution to the analyzed equation in SeparableODE.

**Comment by kziabrowska** [comment]
Description of the current achievements is here: 
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Guide_Source/Source/%5BPL%5D%5BGuide%5D%5BDevelopment%5D%20%C5%9Aledzenie%20podst%C4%99p%C3%B3w%20prac.ipynb
