### ISSUE TITLE
Preparation of a meeting and guide for objective programming and implementation of dynamical systems in DynPy

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#34]
The following actions are to do, in order to prepare the meeting and the guide:

- [x] #282

- [x] #283

- [x] #284

**Comment by MichauSzewczyk** [comment]
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/DYPLOMANCI/Micha%C5%82%20Szewczyk/Praca%20dyplomowa/Guide/guide.ipynb#id=e1916b

**Comment by MichauSzewczyk** [comment]
![image](https://github.com/bogumilchilinski/dynpy/assets/139250443/c91ece4d-5804-4821-8007-0b896affb8b0)

**Comment by bogumilchilinski** [comment]
Guys,

The content looks really nice. However, the other objectives of the meeting scope are missing. Madi (@amvdek ) could you instruct @MichauSzewczyk and @KrzysztofKaczmarzyk what should be included?

**Comment by amvdek** [comment]
Hello, good job guys. I think we could add an example of a well-implemented dynamic system with annotations. Something easy like SpringDamperMassSystem being inherited from SpringMassSystem with both classes codes shown. The _eoms property could appear in report explaining how it is affected by components property as I see both class arguments and __init__ constructor are already described.

**Comment by amvdek** [comment]
SpringMassSystem

https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/Marek%20Skwarka/Shared%20files/modules/dynpy/models/mechanics/trolley.py#line=33

ForcedSpringMassSystem

https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/Marek%20Skwarka/Shared%20files/modules/dynpy/models/mechanics/trolley.py#line=119

These two classes could be used instead classes mentioned earlier.

**Comment by bogumilchilinski** [comment]
Guys,

I agree with @amvdek . We could use previous guide for dynamic systems created by @KrzysztofKaczmarzyk and @grzegorzdl which was leaded by @amvdek as report from some working meeting. @KrzysztofKaczmarzyk , could you share it with us?

**Comment by amvdek** [comment]
Enhanced guide

https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/DYPLOMANCI/Micha%C5%82%20Szewczyk/Praca%20dyplomowa/Guide/Guide.pdf

**Comment by amvdek** [comment]
Done, closed

**Comment by amvdek** [comment]
Every subissue is complete with description and comments. I consider it done and closed.
