### ISSUE TITLE
Supplementing the article regarding semi-active pendulation attenuator with comments (#239 related) - general remarks

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#340]
The aim is to address the reviewers' comments - these were divided into three main categories and assigned to the responsibles.

**General remarks**

 - [x] Abstract - to be extended.
 - [x] Add the recent publications of ES and give a comparison in terms of the paper’s novelty to the latest related ones:
        - ES, 2023, 294: 116744 
        - ES, 2020, 209: 110010
        - ES, 2021, 244: 112743
- [x] Add to introduction some more ES articles: most related references about ATMD with variable stiffness and damping:
        - ES, 2022, 271: 114963
        - JoBE, 2023, 78: 107549
        -  https://doi.org/10.1142/S0219455423400278
- [x] More sentences can be added in section 2 - just to be a bit expanded.
- [x] More details can be proposed for the experiment in section 4.
- [x] Remove the sentence with patent protection.

**Comment by AnnMcCoy** [comment]
Done.
