### ISSUE TITLE
Supplementing the article regarding semi-active pendulation attenuator with comments (#239 related) - substantive remarks

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#341]
**Substantive remarks**

- [x] In Eq. (2) and (3), it is not clear why the initial mass of the lower pendulum member is included. Some explanation is required.
- [x] How this technology could be employed in practice. A better description of how the device could practically function is required.
- [x] Frequency sweeps analysis - a sufficiently fine resolution then draw conclusions about whether resonance is controlled.
- [x] In Fig. 7, why are the spectra shown not smooth? This suggests that the simulations were not at steady-state? Moreover, why has the peak frequency shifted when damping was added?
- [x] Are the "frequency spectra" actually "power spectra"? If so, the labeling and units of the vertical axis are incorrect. If not, what are they showing? What is the purpose of showing power spectra if the system is excited at a single frequency?
- [x] The authors must describe why the second peak at 1Hz was not shown in the experimental work.
- [x] What is the purpose of studying the initial conditions of the system? These are transients that are not of great importance to the dynamic response of a system since they "die out" quite rapidly. It seems these comparisons should be omitted for brevity.
- [x] After Fig. 6, what does "asymptotic stability (lack of the amplitude overloading)" mean?

**Comment by AnnMcCoy** [comment]
Done.
