### ISSUE TITLE
Implementation of LinearODEIntroComponent class that reports part of the solution

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#343]
The goal is to create the LinearODEIntroComponent using ReportComponent class in order to introduce the way of solving the separable ordinary differential equation.

**Comment by kziabrowska** [comment]
Description of the current achievements is here:
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Karolina%20Zi%C4%85browska/TechThrive/Linear_ODE.ipynb#id=5d7aa9
