### ISSUE TITLE
Development of a CarMovementPIDAdjust class

### ISSUE THREAD

**Issue by szymonkozlowski080** [bogumilchilinski/dynpy#352]
Examine an error and make it similar to cells in https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Szymon%20Koz%C5%82owski/Vibrations/CarModel.ipynb.

**Comment by szymonkozlowski080** [comment]
Problem has been examined and work shows that prepared system is not stable and cannot be linearized around requested point. Due to that model has been rearranged.

https://cocalc.com/projects/f5eacfa1-ad37-41af-beea-da7216cf5881/files/Sandbox/Szymon%20Koz%C5%82owski/Praca%20dyplomowa/Praca%20przej%C5%9Bciowa%20-%20mgr/carpy_dev.ipynb

**Comment by bogumilchilinski** [comment]
Class was checked by the following call:

```python
from dynpy.models.mechanics.car import CarMovementPIDAdjust
CarMovementPIDAdjust().eoms
```
