### ISSUE TITLE
Exemplary document that uses WUTThesis class and presents all typical reporting activities

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#364]
Prepare a exemplary document with raw code for thesis template. The document should have all typical and advanced reporting activities. Explain all used LaTeX commands and describe how do they work. Use one of already existing thesis that bases on dynpy's reporting module.

**Comment by amvdek** [comment]
Application example template here:

https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/Application%20examples/%5BTemplate%5D%20Thesis/

All  typical advanced reporting activities are here:

https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Guide_Source/Source/%5BPL%5D%20%5BGuide%5D%20%5BBasics%5D%20DynPy's%20reporting%20module.ipynb
