### ISSUE TITLE
Review of the guide for basic usage of Pandas module

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#365]
The guide for dynamic systems and its utilization is to be reviewed.

**Comment by Mk11-10** [comment]
link to source_code:
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Guide_Source/Source/%5BPL%5D%5BGuide%5DPodstawy%20u%C5%BCywania%20biblioteki%20Pandas%20oraz%20DataFrame.ipynb#id=7246f9
