### ISSUE TITLE
Arrangement of an thesis regarding Trolley with Pendulum model with varying mass

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#371]
Scope of the thesis is as follows:

- [x] Diploma thesis card fullfilment

- [x] Gathering all guides

- [x] Phrasing of the subject of thesis

- [x] Extended perspective on implementation of the modules in dynpy

- [x] Validation of the simulation outcomes

- [x] Proposal of possible applications

- [x] Writing the thesis, introduction, dynpy class structure , examples of dynamic systems, possible applications

- [x] Thesis review

- [x] Thesis improvement

- [x] Final approval of the thesis

**Comment by amvdek** [comment]
Thesis approved
