### ISSUE TITLE
Development of sdof kinematic clutch with springs dynamic system

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#38]
Move the system to appropriate submodule and rewrite the code if needed.

**Comment by Woojaszek2137** [comment]
Code for this system is in this link:
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Jakub%20Szydłowski/KinematicClutchWithSprings.ipynb

**Comment by Woojaszek2137** [comment]
System seems to be okay. Can be closed
