### ISSUE TITLE
Development of interface of ObjectCode class for selection of default listing environment

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#380]
The aim is to fix an interface of `ObjectCode` class in order to provide a feature of easy selection of various listing environment.

**Comment by amvdek** [comment]
Polish letters problem and double displaying are solved. Waiting for sync.

**Comment by amvdek** [comment]
DONE
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/Marek%20Skwarka/Shared%20files/modules/dynpy/utilities/report.py#line=3115
