### ISSUE TITLE
Improvement of the guide related to ODESystem solver (issue #395 related)

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#398]
The goal is to update an existing guide that covers basics of ODESystem solver located in the following CoCalc directory: 
[Guide](https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Guide_Source/Source/%5BPL%5D%20%5BGuide%5D%20%5BProgramming%5DWprowadzenie%20ODESystem.ipynb) .

**Comment by Piotr-Loch** [comment]
Done.
