### ISSUE TITLE
Development of ddof simplified suspension dynamic system

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#40]
Move the system to appropriate submodule and rewrite the code if needed.

**Comment by amvdek** [comment]
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/Marek%20Skwarka/Shared%20files/modules/dynpy/models/mechanics/vehicle.py#line=598
