### ISSUE TITLE
Development of mdof MDoFForcedDisksWithSerialSprings dynamic system

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#41]
Move the system to appropriate submodule and rewrite the code if needed.

**Comment by KrzysztofKaczmarzyk** [comment]
Inheritance from a similar class proposed. Link to the Jypyter notebook below. 
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Maja%20Banasiak%20/2023-07-18-file-1.ipynb#id=9f29c5

**Comment by KrzysztofKaczmarzyk** [comment]
Issue can be closed. Code of the system visible below 

https://github.com/bogumilchilinski/dynpy/blob/673ca0a328c0a72f8bd7a2f2c2bfaaa0a5b865cf/models/mechanics/disk.py#L566-L750

**Comment by KrzysztofKaczmarzyk** [comment]
Issue can be closed.
