### ISSUE TITLE
Improvement of the guide for the meeting (issue #412 related)

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#415]
The goal is to prepare a guide covering numerical simulation with use of ODESystem class

**Comment by KrzysztofKaczmarzyk** [comment]
The guide is available under the following location as and extension for ODESystem guide 
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/%5BWIP%5D%20Guidelines/%5BPL%5D%5BGuide%5D%5BProgramming%5D%5BPL%5D%5BGuide%5D%5BODESystem%5D%20Obs%C5%82uga%20klasy%20ODESystem.pdf
