### ISSUE TITLE
Preparation or improvement of the guide for the meeting for implementation of dynamic systems (issue #423 related)

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#426]
Aim of this issue is to improve a guide for the meeting #423 which is describe in this [Notebook](https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Guide_Source/Source/%5BPL%5D%20%5BGuide%5D%20%5BProgramming%5D%20%5BBasic%5D%20Guide%20-%20programowanie%20obiektowe.ipynb#id=caab11).

**Comment by KrzysztofKaczmarzyk** [comment]
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Guide_Source/Source/%5BPL%5D%20%5BGuide%5D%20%5BProgramming%5D%20%5BBasic%5D%20Guide%20-%20programowanie%20obiektowe.ipynb
