### ISSUE TITLE
Development of ddof dampedshaft dynamic system

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#43]
Move the system to appropriate submodule and rewrite the code if needed.

**Comment by bogumilchilinski** [comment]
https://github.com/bogumilchilinski/dynpy/blob/02f82fb02c26b0413f242710187c437fba0f19c6/models/mechanics/shaft.py#L567C2-L567C2

**Comment by KrzysztofKaczmarzyk** [comment]
Minor changes added since last commit. Issue can be closed.
