### ISSUE TITLE
Preparation of guide for presentation of utilization of beamer document (issue #427 related)

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#430]
Create a jupyter in guide source concerning utilization of beamer.

**Comment by amvdek** [comment]
Application example jupyter is here: 

https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/Application%20examples/%5BTemplate%5D%20Beamer/

**Comment by amvdek** [comment]
Guide:
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Guide_Source/Source/%5BPL%5D%5BGuide%5D%5BBeamer%5D%20Prezentacje.ipynb
