### ISSUE TITLE
Improvement of the guide for the meeting for the application of reporting components (issue #431 related)

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#434]

**Comment by MichauSzewczyk** [comment]
Preparation is done and ready for the meeting.

**Comment by MichauSzewczyk** [comment]
Guide discussed during the meeting:
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/DYPLOMANCI/Micha%C5%82%20Szewczyk/Prezentacja/U%C5%BCycie%20komponent%C3%B3w%20raportuj%C4%85cych%20do%20tworzenia%20dokument%C3%B3w-26-01-2024/U%C5%BCycie%20komponent%C3%B3w%20raportuj%C4%85cych%20do%20tworzenia%20dokument%C3%B3w.ipynb#id=7faaac
