### ISSUE TITLE
Improvement of the guide or description for the meeting for the summary of the 2nd edition of Python course (issue #441 related)

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#444]
Aim of this issue is to improve a guide/description for Python course that is stored in ???.

**Comment by KrzysztofKaczmarzyk** [comment]
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Guide_Source/Source/%5BPL%5D%5BBasics%5D%5BScheduling%5D%20Cykl%20szkoleniowy%20DynPyBasics.ipynb#id=0bbca6
