### ISSUE TITLE
Improvement of the guide for beamer usage and theses reporting (issue #450 related)

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#453]
Improve a guide for creating beamer presentations that is stored in the [Notebook](https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Guide_Source/Source/%5BPL%5D%5BGuide%5D%5BBeamer%5D%20Prezentacje.ipynb).

**Comment by amvdek** [comment]
Guide updated
