### ISSUE TITLE
Preparation or improvement of the guide for usage of dynamic systems and reporting  (issue #462 related)

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#465]
Improve a guide for creating beamer presentations that is stored in the [Notebook](https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Guide_Source/Source/%5BPL%5D%5BGuide%5D%5BBeamer%5D%20Prezentacje.ipynb).

**Comment by kziabrowska** [comment]
The  updated guide can be found here: [Notebook](https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Guide_Source/Source/Output/%5BPL%5D%5BGuide%5D%5BDynpy%5DPodstawy%20obs%C5%82ugi%20system%C3%B3w%20dynamicznych%20-%20wci%C4%85garka.pdf)
