### ISSUE TITLE
Improvement of solver selection in MultiTimeScaleSolution class 

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#466]
Implement if statement for general solution, which will select a proper solver depending on result of jacobian of odes.

**Comment by amvdek** [comment]
Code:
https://cocalc.com/projects/f5eacfa1-ad37-41af-beea-da7216cf5881/files/Shared%20files/modules/dynpy/solvers/nonlinear.py#line=512
