### ISSUE TITLE
Translation of guide for basic usage of DynPy module

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#49]
Translation of the guide being assigned to #44 is needed.

**Comment by SabinaSyp** [comment]
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Jakub%20Szyd%C5%82owski/Guide-CoCalc-EN.ipynb

**Comment by bogumilchilinski** [comment]
Closed as finished.
