### ISSUE TITLE
Utilization of electric engine model for DynPy's assessment purposes (issue #491 related)

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#493]
Use the existing model of an electric engine in paper. Utilize the equations of motion and simulations. Prepare the description in English.

**Comment by amvdek** [comment]
DONE, [link to module](https://cocalc.com/projects/f5eacfa1-ad37-41af-beea-da7216cf5881/files/Shared%20files/modules/dynpy/models/electric/engine.py#line=64)
