### ISSUE TITLE
Preparation of guidelines for thesis submission procedure

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#494]
Preparation of a draft for the thesis submission procedure. Version 1.0

**Comment by MichauSzewczyk** [comment]
[Notebook](https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Guide_Source/Source/%5BPL%5D%5BGuide%5D%5BBasics%5D%20Proces%20pisania%20pracy%20dyplomowej.ipynb)
[PDF](https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/%5BWIP%5D%20Guidelines/%5BPL%5D%5BGuide%5D%5BBasics%5D%20Proces%20pisania%20pracy%20dyplomowej.pdf)

**Comment by MichauSzewczyk** [comment]
Draft has been prepared, following links to the document:
[Notebook](https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Guide_Source/Source/%5BPL%5D%5BGuide%5D%5BBasics%5D%20Proces%20pisania%20pracy%20dyplomowej.ipynb)
[PDF](https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/%5BWIP%5D%20Guidelines/%5BPL%5D%5BGuide%5D%5BBasics%5D%20Proces%20pisania%20pracy%20dyplomowej.pdf)
