### ISSUE TITLE
Template for description of a engineering drawing case

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#50]
There is a need of template (exemplary description and drawing) of selected case as example of solving and reporting method.

**Comment by Woojaszek2137** [comment]
The code for this template can be found in this Jupyter:
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Jakub%20Szydłowski/%5BTemplate%5D%20ED/guide_engeneering_drawing_PL.ipynb
