### ISSUE TITLE
Development of module containing schemes

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#500]
Aim of this issue is to develop a module which will contain schemes and collecting existing schemes inside this module.

**Comment by amvdek** [comment]
Module:

https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/Marek%20Skwarka/Shared%20files/modules/dynpy/utilities/templates/schemes.py
