### ISSUE TITLE
Development of ddof DampedElasticPendulum dynamic system

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#51]
Move the system to appropriate submodule and rewrite the code if needed.

**Comment by Woojaszek2137** [comment]
Code for this system can be found  in this Jupyter:
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Jakub%20Szydłowski/DoubleElasticPendulum/DoubleElasticPendlum.ipynb#id=73c311
