### ISSUE TITLE
Relocation of the method for fast setup of `NumericalAnalysisDataFrame`  to `AnalyticalSolution` class

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#510]
Aim of this issue is to relocate method for fast setup of `NumericalAnalysisDataFrame`  to `AnalyticalSolution` class.

**Comment by amvdek** [comment]
DONE [link to module](https://cocalc.com/projects/f5eacfa1-ad37-41af-beea-da7216cf5881/files/Shared%20files/modules/dynpy/dynamics.py#line=1875)
