### ISSUE TITLE
Implementation of dependency handling that simplifies the expression

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#516]
Aim of this issue is to implement dependency handling that simplifies expression.

**Comment by bogumilchilinski** [comment]
from dynpy.models.mechanics import ForcedSpringMassSystem
    ForcedSpringMassSystem()._ode_system.to_canonical_form()

**Comment by mopar4or2no6car** [comment]
Change of cannonical form coefficients display from dict to equations
