### ISSUE TITLE
Development of a latex preview for dependencies handling using the `_repr_latex_` method

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#517]
Aim of this issue is to develop latex preview for dependencies handling using the `_repr_latex_ ` method.

**Comment by MichauSzewczyk** [comment]
'''
from dynpy.solvers.linear import *
import sympy
t = Symbol('t')
Omega, omega = symbols('Omega omega',positive = True)
x = Function('x')(t)
ode = ODESystem(odes=Matrix([x.diff(t, t) + omega**2 * x - sin(Omega*t)]), dvars=Matrix([x]), ode_order=2)
display(ode)
'''
