### ISSUE TITLE
Preparation of meeting and guide for property and classmethod decorators and dynamical systems implementation

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#52]
The following actions are to do, in order to prepare the meeting and the guide:

- [x] #285

- [x] #286

- [x] #287

**Comment by Woojaszek2137** [comment]
@KrzysztofKaczmarzyk send me  the final version of the guide for the issue #29, Please.

**Comment by KrzysztofKaczmarzyk** [comment]
issue can be closed
