### ISSUE TITLE
Preparation or improvement of the guide for implementation of dynamic systems (issue #526 related)

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#529]
The goal is to improve the guide covering procedure of dynamic system implementation. Use the following [Notebook](https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Guide_Source/Source/%5BPL%5D%20%5BGuide%5D%20%5BProgramming%5D%20%5BBasic%5D%20Guide%20-%20programowanie%20obiektowe.ipynb).

**Comment by amvdek** [comment]
Guide does not need improvement in this iteration of dynpy basics.
