### ISSUE TITLE
Implementation of `with_ics` method for NumericalAnalysisDataFrame

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#531]
The goal is to implement a `with_ics` method that handles initial conditions as ODESolution class.

**Comment by fgawinski** [comment]
'with_ics' method has been added with two auxiliary function - 'insert_ics', 'multiply_list'.

Ics can be define as list, tuple or dictionary. Dictionary support is done poorly for now and has to be reimplemented in the future.
