### ISSUE TITLE
Implementation of `CodeFrame` class that provides beamer frames being compatible with code listings

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#536]
The goal is to implement a `CodeFrame` class that provides beamer frames compatible with code listings.

**Comment by szymonkozlowski080** [comment]
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/Marek%20Skwarka/Shared%20files/modules/dynpy/utilities/report.py

Lines 2748 - 2796

Ready to close
