### ISSUE TITLE
Implementation of `_as_na_df` method for dynamics systems

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#538]
The goal is to create simple method or property that adapts or maps `_as_na_df` method from `ODESystem` for dynamic systems.

**Comment by bartekvv4** [comment]
Method _as_na_df for dynamics systems has been implemented to dynpy,models.mechanics.principles into ComposedSystem class.
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/Marek%20Skwarka/Shared%20files/modules/dynpy/models/mechanics/principles.py
Example of use:
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Bartosz%20Wanat/Develpomental.ipynb
