### ISSUE TITLE
Implementation of an interface for `_as_na_df` method for dynamics system and `ODESystem` class

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#539]
The goal is to create simple method or property that calls `_as_na_df` method from `ODESystem` class and dynamic systems.

**Comment by bartekvv4** [comment]
Method _as_na_df for dynamics systems has been implemented to dynpy,models.mechanics.principles into ComposedSystem class.
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/Marek%20Skwarka/Shared%20files/modules/dynpy/models/mechanics/principles.py
