### ISSUE TITLE
Development of SDOFDrivetrainVehicleSystem dynamic system 

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#55]
to move and fix within tmac.py

**Comment by Woojaszek2137** [comment]
Fixed system can found in this Jupyter :
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Jakub%20Szydłowski/Systemy/SDOFDrivetrainVehicleSystem.ipynb
It has been also moved to tmac.py.
Issue can be closed.
