### ISSUE TITLE
Preparation or improvement of the guide for development of papers (issue #549 related)

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#552]
Guide for the papers development is to be prepered or improved. Use the following [Notebook](https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Guide_Source/Source/%5BPL%5D%5BGuide%5D%5BBasics%5D%20Wprowadzenie%20do%20raportowania%20w%20Python-ie%20oraz%20podstawy%20stosowania%20komoponetów%20raportujących.ipynb).

**Comment by Woojaszek2137** [comment]
Done
