### ISSUE TITLE
Preparation or improvement of the guide for scheduling of the 4th edition of Python course (issue #555 related)

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#558]
The goal is to prepare a schedule for 4th edition of DynPy basics meetings that is stored in the [Notebook](https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Guide_Source/Source/%5BPL%5D%5BBasics%5D%5BScheduling%5D%20Cykl%20szkoleniowy%20DynPyBasics.ipynb).

**Comment by Woojaszek2137** [comment]
Done
