### ISSUE TITLE
Implementation of class for model of trolley with varying mass PTMD (issue #563 related)

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#564]
Class for model of trolley with varying mass PTMD is to be implemented.

**Comment by Piotr-Loch** [comment]
Done. Model of pendulum with varying mass has been implemented in dynpy/models/mechanics/pendulum.py.

from dynpy.models.mechanics.trolley import TrolleyWithVaryingMassDamper
TrolleyWithVaryingMassDamper().eoms
