### ISSUE TITLE
Implementation of `IntroToCocalcGuide` class that inherits by `Guide` document

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#584]
Class in `documents.document.py` is to be implemented. Reporting components from `guides.pl.py`  regarding `IntroToCocalcGuide` should be used.

**Comment by Woojaszek2137** [comment]
Done

**Comment by Woojaszek2137** [comment]
![image](https://github.com/bogumilchilinski/dynpy/assets/128740293/a427a6b0-e8df-4ad5-868a-3e545caf06fe)

**Comment by Woojaszek2137** [comment]
from dynpy.utilities.documents.document import IntroToCocalcGuide
    IntroToCocalcGuide(None);
