### ISSUE TITLE
Implementation of `UsageOfDynamicSystemsGuide` class that inherits by `Guide` document

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#585]
Class in `documents.document.py` is to be implemented. Reporting components from `guides.pl.py`  regarding `UsageOfDynamicSystemsGuide` should be used.

**Comment by Woojaszek2137** [comment]
Done

**Comment by Woojaszek2137** [comment]
![obraz_2024-04-08_133817289](https://github.com/bogumilchilinski/dynpy/assets/128740293/b4ea90e7-572a-4dfc-9bda-d6a080f63eca)

**Comment by Woojaszek2137** [comment]
from dynpy.utilities.documents.document import UsageOfDynamicSystemsGuide
  UsageOfDynamicSystemsGuide(None);
