### ISSUE TITLE
Implementation of `WeakCubicNonlinearODE` class that represents exemplary ODE

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#587]
The goal is to upload weak nonlinear stiffness x^3 simulations into SolverDescription paper.

**Comment by kziabrowska** [comment]
Code to copy:
`from dynpy.models.odes.nonlinear import CubicWeakOscillatorMSM`
`CubicWeakOscillatorMSM.from_reference_data()`
