### ISSUE TITLE
Development of MDoFForcedSimpleDisksWithParallelSprings dynamic system 

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#59]

**Comment by Woojaszek2137** [comment]
Fixed system can be found in this Jupyter:
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Jakub%20Szydłowski/Systemy/MDoFForcedSimpleDisksWithParallelSprings.ipynb#id=faef8b
Also it has been moved to disk.py.
Issue can be closed.
