### ISSUE TITLE
Implementation of DampedEngineMount basic element

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#6]
New basic element is to implement is module 'elements.py'. It should be inherited from similar class being implemented within scope of the module if possible.

**Comment by amvdek** [comment]
@bogumilchilinski 

DampedEngineMount

https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/Marek%20Skwarka/Shared%20files/modules/dynpy/models/elements.py#line=494

**Comment by amvdek** [comment]
Check the implementation

**Comment by amvdek** [comment]
DONE
