### ISSUE TITLE
Development of MDoFForcedSimpleDisksWithSerialSprings dynamic system 

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#60]
to merge with MDoFForcedDisksWithSerialSprings

**Comment by lemichal** [comment]
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Michal%20Kalinowski/serial_springs_three-disks.ipynb

**Comment by Woojaszek2137** [comment]
Fixed system can be found in this Jupyter:
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Jakub%20Szydłowski/Systemy/MDoFForcedSimpleDisksWithSerialSprings.ipynb#id=638650

It has been moved to disk.py.
Issue can be closed.
