### ISSUE TITLE
Implementation of `RollingBar` class that represents dynamic system

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#610]
New dynamic system is to implement is module `pendulum.py`. It should be inherited from similar class being implemented within scope of the module if possible.

**Comment by Mk11-10** [comment]
@kjaskiel co tu trzeba zrobić?

**Comment by MichalKacperek** [comment]
The code was checked with the following call:
```
from dynpy.models.mechanics import RollingBar
from dynpy.utilities.documents.document import DynSysOverviewReport
DynSysOverviewReport(reported_object=RollingBar())
```
