### ISSUE TITLE
Implementation of `DynSysIntroComponent` class that creates a part of a report

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#612]
Class is to implement in `guides.en.py` module that is a reporting component of introduction to dynamic systems reimplementation.

**Comment by Danielstryjewski** [comment]
DynSysIntroComponent class implemented in guides.pl.py

**Comment by Danielstryjewski** [comment]
Code to call class:
`
from dynpy.utilities.components.guides.pl import*

DynSysIntroComponent(None)
`
