### ISSUE TITLE
Implementation of `ConstrainsReactions` element that represents dynamic components

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#615]

**Comment by Mk11-10** [comment]
from sympy import*
import numpy as np
from dynpy.models.elements import Force, Element
import sympy as sym
from dynpy.models.mechanics.principles import*
import math


class ConstrainsReaction(Element):
    """
    Creates enforcement.
    """

    scheme_name = ''
    real_name = ''
    def __init__(self,
                 constrain = None,
                 pos1 = None,
                 qs = None,
                 ivar=Symbol('t'),
                 frame = base_frame):

        self.constrain = constrain
        self._pos1 = pos1
#         self.force=force
        if qs is None:
            qs = [pos1]

        else:
            qs = qs


        if isinstance(pos1, Point):
            P = pos1
            if qs is None:
                diffs=P

                qs= [deriv.args[0] for deriv in diffs]
                print(qs)
        else:

            P = Point('P')
            P.set_vel(frame,pos1.diff(ivar)*frame.x)

            force = 0
            R = Symbol('R')
            for coord  in qs:

                force=+self.constrain.diff(coord)*frame.x*R


        forcelist=[(P,force)]

        #display(forcelist)

        super().__init__(0, qs=qs, forcelist=forcelist, frame=frame, ivar=ivar)

    def get_default_data(self):
        t=self.ivar
        F0=Symbol('F_0',positive=True)
        self.default_data_dict={
            # self.force:[F0*no for no in range(1,10)],
        }
        return {**super().get_default_data(),**self.default_data_dict}

    def _get_virtual_work(self):
        return Eq(Symbol('\delta W'), Symbol(latex(self.force)) * Symbol(f'\delta({latex(self._pos1)})')  )    


x = dynamicsymbols('x')
y = Symbol('y')
r = Symbol('r')

ConstrainsReaction(x+y,pos1 = x).eoms
