### ISSUE TITLE
Development of `.base_setup` method of Guide class that defines document form

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#619]
The goal is to add examples to output of `.base_setup` method of `Guide` from `dynpy.utilities.documents.document.py` . It should include `Picture` class reporting and how to prepare simple document.

**Comment by bartekvv4** [comment]
Examples has been added to Guide from dynpy.utilities.documents.document.py including Picture class reporting and how to create a simple document. 
(Lane 263 in module)
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/Marek%20Skwarka/Shared%20files/modules/dynpy/utilities/documents/document.py

**Comment by bartekvv4** [comment]
To generate exemplary document it should be used simple formula:
```
_from dynpy.utilities.templates.document import Guide
Guide.base_setup()_
```
