### ISSUE TITLE
Enhancement of `numerical_analysis` and `_as_na_df` methods that provides `t_span` argument

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#620]
The goal of issue is preparing additional `_as_na_df` method argument that allows to prepare Numerical Analysis DataFrame with extended index of time span.

**Comment by szymonkozlowski080** [comment]
https://cocalc.com/projects/f5eacfa1-ad37-41af-beea-da7216cf5881/files/Shared%20files/modules/dynpy/solvers/linear.py

https://cocalc.com/projects/f5eacfa1-ad37-41af-beea-da7216cf5881/files/Shared%20files/modules/dynpy/models/mechanics/principles.py

https://cocalc.com/projects/f5eacfa1-ad37-41af-beea-da7216cf5881/files/Shared%20files/modules/dynpy/solvers/numerical.py

https://cocalc.com/projects/f5eacfa1-ad37-41af-beea-da7216cf5881/files/Sandbox/Szymon%20Koz%C5%82owski/Tasks/variable_mass_class_development.ipynb

Changes and usage have been shown in following links
