### ISSUE TITLE
Maintenance of `ForcedSpringMassSystem` class which is dynamic system representation

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#636]
New system is to implement is module `trolley.py`. It should be inherited from similar class being implemented within scope of the module if possible.

**Comment by Piotr-Loch** [comment]
Issue can be closed. Forced spring mass system has been fixed (get numerized parameters has been added).

**Comment by bogumilchilinski** [comment]
Issue description is missing.

**Comment by Piotr-Loch** [comment]
The `ForcedSpringMassSystem` class has been implemented. The code was checked with the following call:
```python
from dynpy.models.mechanics import ForcedSpringMassSystem
from dynpy.utilities.documents.document import DynSysOverviewReport
DynSysOverviewReport(reported_object=ForcedSpringMassSystem())
