### ISSUE TITLE
Implementation of `DiskOnTrolleyWithFriction` class that represents dynamic system

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#637]

**Comment by kjaskiel** [comment]
The #DiskOnTrolleyWithFriction class has been implemented. The code was checked with the following call:

from dynpy.models.mechanics import DiskOnTrolleyWithFriction
from dynpy.utilities.documents.document import DynSysOverviewReport
DynSysOverviewReport(reported_object=DiskOnTrolleyWithFriction());
