### ISSUE TITLE
Maintenance of `SimulationsComponent` class that is component of `UsageOfDynamicSystemsGuide`

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#642]
The goal of the issue is to review and/or improve the class that implements report component within `guides.en.py` module,

**Comment by Fyla** [comment]
The code was checked with the following call:

```
from dynpy.utilities.documents.document import UsageOfDynamicSystemsGuide

UsageOfDynamicSystemsGuide()
```

and the content of `SimulationsComponent `was checked
