### ISSUE TITLE
Maintenance of `IntroToPandasGuide` class that provides guide for basics of Pandas library

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#648]
The scope of the issue includes maintenance of the following classes:

- [x] #651 

- [x] #652

- [x] #653

- [x] #654

**Comment by MichauSzewczyk** [comment]
Maintenance has been processed.

**Comment by bogumilchilinski** [comment]
Call code is missing. Please add the following comment:

> Class was checked by the following call:
> 
> ```
> #```python
> #call_code
> #```
> ```

**Comment by bartekvv4** [comment]
call code:
from dynpy.utilities.documents.document import IntroToPandasGuide
IntroToPandasGuide(None);

**Comment by bartekvv4** [comment]
Call code
from dynpy.utilities.documents.document import IntroToPandasGuide
IntroToPandasGuide(None);

**Comment by bartekvv4** [comment]
The code was checked with the following call:

```python
from dynpy.utilities.documents.document import IntroToPandasGuide
IntroToPandasGuide(None);
```
