### ISSUE TITLE
Implementation of `BasicsOfODESystemGuide` class that inherits by `Guide` document

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#650]
Class in `documents.document.py` is to be implemented. The components (from `guides.en.py`) to use are as follows:

- [x] #605  

- [x] #606  

- [x] #607  

- [x]  #608 

- [x]  #609
 
- [x]  #611

**Comment by Woojaszek2137** [comment]
dynpy.utilities.documents.document import BasicsOfODESystemGuide
    BasicsOfODESystemGuide();

**Comment by Woojaszek2137** [comment]
Done
