### ISSUE TITLE
Development of environment for handling modules structure and listing of classes

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#655]
The following activities are to do:

- [x] assignment of tasks;

- [x] presentation of requirements that need to be implemented (code, issues, other things);

- [x] presentation of performed activities;

- [x] #860

- [x] #876 

- [x] #888

Methods, functions or classes to implement are as follows:

- [x] #773 

- [x] #894 

- [x] #895 

- [x] #896 

- [x] #897

**Comment by Danielstryjewski** [comment]
Class `ModuleStructure` is stored in `dynpy/utilities/creators.py`

**Comment by Danielstryjewski** [comment]
Update: 

- lister method returns list of classes with parent submodule in tuple format

- `tree` method was added to print class list in tree format.

- Added `help()` with class and methods description

**Comment by Danielstryjewski** [comment]
Added functionality to get import command for any class

The code was checked with the following code:

```python
from dynpy.utilities.creators import ModuleStructure

ModuleStructure.get_import('ObjectCode')
```

**Comment by Danielstryjewski** [comment]
All subtasks are closed, task finished
