### ISSUE TITLE
Implementation of ODECharacteristicPolynomialComponent and ODECharacteristicPolynomialCodeComponent classes 

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#66]
Implementation of ODESystem based reporting components returning a characteristic polynomial for particular system and relevant code presenting usage of method to obtain the same output displayes using Mardkown

**Comment by KrzysztofKaczmarzyk** [comment]
Progress of the work can be tracked in the following jupyter notebook: 
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Krzysztof%20Kaczmarzyk/CharacteristicPolynomial.ipynb#id=ef7871

**Comment by KrzysztofKaczmarzyk** [comment]
Both components implemented successfully. Issue can be closed.
