### ISSUE TITLE
Preparation of meeting and guide for creating of quiz questions

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#70]
1. Introduction to the quiz questions generation
2. Making a choice of a dynamic system
3. Creating a method which returns a desired value
4. Creating an object TitledCoefQuestion
5. Making a preview of a new question

Ad. Preperation of a guide

**Comment by szymonkozlowski080** [comment]
02.08 (Wednesday) 18:00 - meet
