### ISSUE TITLE
Maintenance of `Engine` class which is dynamic system representation

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#707]
The following problems have to be checked or fixed, in order to ensure the correctness of implemented system:

- [x] checking if a class is executable,

- [x] validation of figures for schemes and real examples,

- [x] validation of reference parameters,

- [x] validation of random parameters,

- [x] validation of  description of parameters,

- [x] validation of units.

**Comment by MichalKacperek** [comment]
The code was checked with the following call:
```
from dynpy.models.mechanics.engine import  Engine
from dynpy.utilities.documents.document import DynSysOverviewReport
DynSysOverviewReport(reported_object=Engine())
```
