### ISSUE TITLE
Maintenance of `UndampedVehicleSuspension` class which is dynamic system representation

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#708]
The following problems have to be checked or fixed, in order to ensure the correctness of implemented system:

- [x] checking if a class is executable,

- [x] validation of figures for schemes and real examples,

- [x] validation of reference parameters,

- [x] validation of random parameters,

- [x] validation of  description of parameters,

- [x] validation of units.

**Comment by Fyla** [comment]
The code was checked with the following code:
from dynpy.models.mechanics import UndampedVehicleSuspension
from dynpy.utilities.documents.document import DynSysOverviewReport
DynSysOverviewReport(reported_object=UndampedVehicleSuspension())
