### ISSUE TITLE
Maintenance of `BeamBridge` class which is dynamic system representation       

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#711]
The following problems have to be checked or fixed, in order to ensure the correctness of implemented system:

- [x] checking if a class is executable,

- [x] validation of figures for schemes and real examples,

- [x] validation of reference parameters,

- [x] validation of random parameters,

- [x] validation of  description of parameters,

- [x] validation of units.

**Comment by amvdek** [comment]
DONE
