### ISSUE TITLE
Implementation of `GithubIssueReportComponent` class that creates a part of a report

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#713]
Class is to implement in `guide.en.py` module that creates a part (reporting component - formally child of `ReportComponent` class) of guide or report for `ReportComponent` class.

**Comment by lsikor** [comment]
Added class GithubIssueReportComponent to guide.en.py

To import use:
from dynpy.utilities.components.guides.en import GithubIssueReportComponent

#PYTHON
