### ISSUE TITLE
Implementation of `UsageOfGitHubInterfacesComponent` class that creates a part of a report

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#714]
Class is to implement in `guide.en.py` module that creates a part (reporting component - formally child of `ReportComponent` class) of guide or report for `ReportComponent` class.

**Comment by lsikor** [comment]
DONE

from dynpy.utilities.components.guides.en import UsageOfGitHubInterfacesComponent
UsageOfGitHubInterfacesComponent(None);
