### ISSUE TITLE
Common space for all examples of solutions of mechanical problems

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#73]
List of exemplary solutions of mechanical problems is needed to create a common space to finish with development of these. Let's place all of these in temporary folder which is _./Mechanika/[WIP] Exemplary solutions_ and renamed in consistent way.

**Comment by kziabrowska** [comment]
link to the common space: https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/Mechanika/%5BWIP%5D%20Exemplary%20solutions/

**Comment by Woojaszek2137** [comment]
All examplary solutions of Mechanical problems were moved to'./Mechanika/[WIP] Exemplary solutions' directory. Each file got assigned to specific branch of Mechanics.
