### ISSUE TITLE
Common space for templates and tutorials of typically used documents

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#74]
List of templates and tutorials is needed to create a common space for these documents. Let's create temporary folder (e.g. _./Guidelines/[WIP] Templates and Examples_) and place all documents there with consistent names.

**Comment by bogumilchilinski** [comment]
Guys (@SabinaSyp @lemichal),
 
Here you will find current version of the pool for commonly used documents:
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/Application%20examples/

**Comment by lemichal** [comment]
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Michal%20Kalinowski/serial_springs_three-disks.ipynb
