### ISSUE TITLE
Implementation of `ReportingModuleIntroComponent` class that creates a part of a report

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#746]
Class is to implement in `guide.en.py` module that creates a part (reporting component - formally child of `ReportComponent` class) of guide for reporting module.

**Comment by Piotr-Loch** [comment]
''
from dynpy.utilities.components.guides.en import ReportingModuleIntroComponent
ReportingModuleIntroComponent(None);
''
