### ISSUE TITLE
Implementation of `CurrentContainerComponent` class that creates a part of a report

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#749]
Class is to implement in `guide.en.py` module that creates a part (reporting component - formally child of `ReportComponent` class) of guide for reporting module.

**Comment by Danielstryjewski** [comment]
`from dynpy.utilities.components.guides.en import PictureComponent

PictureComponent(None)`

**Comment by bogumilchilinski** [comment]
```
from dynpy.utilities.components.guides.en import CurrentContainerComponent
CurrentContainerComponent(None);
```
