### ISSUE TITLE
Tutorial for basic usage of DynPy's reporting module

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#75]
The essential information about reporting module for DynPy are to describe. The guide has to contain basic information on how to create a simple text document using the basic classes, i.e. reporting modules such as ReportText, Markdown or Picture.

Similar report can be found in #44 .

Main elements to do:

- [x] #81

- [x] #82

- [x] #83

**Comment by Eratostenes** [comment]
Update comment

**Comment by Woojaszek2137** [comment]
Done, can be closed.
