### ISSUE TITLE
Implementation of `GitSynchroPanelAccessComponent` class that creates a part of a report

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#750]
Class is to implement in `guide.en.py` module that creates a part (reporting component - formally child of `ReportComponent` class) of guide or report for `ReportComponent` class.

**Comment by Woojaszek2137** [comment]
from synpy.utilities.components.guides.en import GitSynchroPanelAccessComponent
    
    GitSynchroPanelAccessComponent(None);
