### ISSUE TITLE
Implementation of `DocumentGenerationComponent` class that creates a part of a report

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#754]
Class is to implement in `guide.en.py` module that creates a part (reporting component - formally child of `ReportComponent` class) of guide for reporting module.

**Comment by Danielstryjewski** [comment]
Class was checked by the following call:

```python
from dynpy.utilities.components.guides.en import DocumentGenerationComponent
DocumentGenerationComponent(None);
```
