### ISSUE TITLE
Translation of guide for basic of objective oriented programming

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#76]
Translation of the guide being assigned to #34 is needed.

**Comment by lemichal** [comment]
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/DYPLOMANCI/Micha%C5%82%20Szewczyk/Praca%20dyplomowa/Guide/guide-en.ipynb
