### ISSUE TITLE
Schedule of Effective Python internship meetings

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#77]
Table of meetings:

- [x] bogumilchilinski/dynpy#21

- [x] bogumilchilinski/dynpy#20 

- [x] bogumilchilinski/dynpy#34 

- [x] bogumilchilinski/dynpy#52

- [x] bogumilchilinski/dynpy#53

- [x] bogumilchilinski/moodle#66 

- [x] bogumilchilinski/dynpy#110 

- [x] bogumilchilinski/dynpy#190

- [x] bogumilchilinski/dynpy#191

- [x] bogumilchilinski/dynpy#192

- [x] bogumilchilinski/dgeometry#15

- [x] bogumilchilinski/moodle#46

- [x] bogumilchilinski/moodle#70

- [x] bogumilchilinski/moodle#50 

- [x] bogumilchilinski/dynpy#196

- [x] bogumilchilinski/dgeometry#7

- [x] bogumilchilinski/dynpy#214

- [x] bogumilchilinski/dynpy#228

- [x] bogumilchilinski/dynpy#188

- [x] bogumilchilinski/dgeometry#11

- [x] bogumilchilinski/dynpy#266

- [x] #298 

- [x] #315 

- [x] #326 

- [x] #353 

- [x] #362 

Maintenance of the internship meetings timetable:

- [x] bogumilchilinski/dynpy#221

- [x] #295

- [x]  #296

- [x] #297

- [x] #302

**Comment by bogumilchilinski** [comment]
Guys, Could you complete a list of meetings with related issues?

**Comment by amvdek** [comment]
@bogumilchilinski done

**Comment by Woojaszek2137** [comment]
#191 - Tworzenie automatycznych raportów w klasie ODESystem - 24.08.23

#190 - Utrzymanie klas opisujących systemy mechaniczne - 19.08.23

#189 - Dynamika układu punktów materialny - 12.08.23

#188 - Utrzymanie kodu systemów dynamicznych - 08.08.23
