### ISSUE TITLE
Implementation of `development` submodule in `components.guides` module

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#776]
The goal is to implement given submodule within the scope of `components.guides` module and prepare the methods that provide interface for translation. The following objectives are to achieve:

- [x] preparation of `en.py` submodule with bases classes;

- [x] preparation of `pl.py` submodule with inheritance;

**Comment by lsikor** [comment]
The code was checked with the following code:

```python
from dynpy.utilities.documents.guides import InterimProjectGuidelines
InterimProjectGuidelines(None)
```
