### ISSUE TITLE
Relocation of systems from chair.py and chairmodels.py  modules and its rejection

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#79]
All old classes from module have to be moved to appropriate destination.

**Comment by mopar4or2no6car** [comment]
chair.py and chairmodels.py were deleted from the dynpy main catalog. New, temporary wheelchairs_TEMP.py file was created in dynpy.models.mechanics to stash a code defined in them. The oldest version of ChairModel5DOF class was deleted and replaced by newer version compatible with current approach for coding dynamic systems. Codes appearing to be trash were moved to the wheelchairs_TEMP.py file and commented for further inspection. 

Comparison between already existing chair.py file in mechanics catalog and new TEMP file is needed to create fully functional module.

Current problem: differences between DampedChair4DOF() (the newest) and Chair5DOF() (older version) equations of motion.

Proposed solution: creating a new class Chair5DOF() compatible with current dynamic system approach basing on the oldest, non-compatible version.

**Comment by bogumilchilinski** [comment]
Module was rejected and systems were moved to `models.mechanics.chair` module.

The code was checked with the following call:

```python
from dynpy.models.mechanics.chair import *
```
