### ISSUE TITLE
Development and maintenance of `NumericalAnalysisDataFrame` class

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#80]
The goal is to maintain the `NumericalAnalysisDataFrame` class.  Actions to do are as follows:

- [x] #503 

- [x] #510 

- [x] #513 

- [x] #531

**Comment by fgawinski** [comment]
Help function to this class and its functions (such as from_model, perform_simulations) have been made.

**Comment by fgawinski** [comment]
In my opinion job on this module is done.

I am closing this issue.

**Comment by fgawinski** [comment]
'with_ics' method has been added with two auxiliary function - 'insert_ics', 'multiply_list'. 

Ics can be define as list, tuple or dictionary. Dictionary support is done poorly for now and has to be reimplemented in the future.

**Comment by fgawinski** [comment]
The code was checked with the following code:

```python
from dynpy import *
from dynpy.solvers.linear import *
from sympy import *
from dynpy.utilities.adaptable import *

m, c, k, F = symbols('m c k F', positive = True)
t = Symbol('t')
x = Function('x')(t)

subs_data = {
            m: 10,
            c: 5,
            k: 2,
            }

tspan_1=np.linspace(0,10, 100)
ode_sys = ODESystem(odes=Matrix([k*x + F + c*x.diff(t)]), dvars=Matrix([x]), ode_order=1)

X = [x, x.diff(t)]
num_df = NumericalAnalysisDataFrame.from_model(ode_sys.solution.with_ics([1]),
    F,
    [1, 2, 5],
    reference_data=subs_data,
    coordinates=X,
    index=pd.Index(tspan_1,name=t),
    ics=None
    )

display(num_df)

````
