### ISSUE TITLE
Initial release of tutorial for basic usage of DynPy's reporting module

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#82]
The essential information about reporting module for DynPy are to describe. The guide has to contain basic information on how to create a simple text document using the basic classes, i.e. reporting modules such as ReportText, Markdown or Picture.
Similar report can be found in [#44](https://github.com/bogumilchilinski/dynpy/issues/44) .

**Comment by Woojaszek2137** [comment]
Done, can be closed.
