### ISSUE TITLE
Development od MDoFPendulumWithRod dynamic system

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#84]
New system is to implement is module _pendulum.py_. It should be inherited from similar class being implemented within scope of the module if possible.

**Comment by KrzysztofKaczmarzyk** [comment]
Components implemented successfully, therefore issue can be closed.

**Comment by KrzysztofKaczmarzyk** [comment]
System implemnted to pendulum.py module. Issue can be closed
