### ISSUE TITLE
Development of InclinedSpringMassSystem dynamic system

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#85]
New system is to implement is module principles.py. It should be inherited from similar class being implemented within scope of the module if possible.

**Comment by KrzysztofKaczmarzyk** [comment]
Class has been implemented in trolley.py module. Issue can be closed. 

https://github.com/bogumilchilinski/dynpy/blob/c043c9d9944e415c610463fe59ae9109c1587d77/models/mechanics/trolley.py#L2099-L2191
