### ISSUE TITLE
Development of PlanetaryGearWithSpring dynamic system

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#86]
New system is to implement is module gear.py. It should be inherited from similar class being implemented within scope of the module if possible.

**Comment by KrzysztofKaczmarzyk** [comment]
Class name has been chanched to PendulumWithRoller due to characteristics closer to pendulum rather than gearbox. Class has been implemented and issue can be closed. 

https://github.com/bogumilchilinski/dynpy/blob/c043c9d9944e415c610463fe59ae9109c1587d77/models/mechanics/pendulum.py#L1194-L1321
