### ISSUE TITLE
Arrangement and execution of the meeting for implementation of generators of dynamic systems lists (issue #860 related)

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#862]
The goal is to arrange and execute the meeting for implementation of generators of dynamic systems lists. The following things should be prepared:

- [ ] scope and schedule of meeting (in one week);

- [ ] conducting team (in two weeks);

- [ ] guide or instructions with examples (one week before meeting);

- [ ] announcement (in Slack and Teams channel) with basic information (conducting persons, date,scope,schedule) (one week before meeting);

- [ ] exemplary code in Jupyter (link) (one week before meeting).

**Comment by fgawinski** [comment]
Meeting was carried out. I'm closing this issue.
