### ISSUE TITLE
Arrangement and execution of the meeting for calling of recently implemented dynamic systems (issue #864 related)

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#866]
The goal is to arrange and execute the meeting for calling of recently implemented dynamic systems. The following things should be prepared:

- [x] scope and schedule of meeting (in one week);

- [x] conducting team (in two weeks);

- [x] guide or instructions with examples (one week before meeting);

- [x] announcement (in Slack and Teams channel) with basic information (conducting persons, date,scope,schedule) (one week before meeting);

- [x] exemplary code in Jupyter (link) (one week before meeting).

**Comment by bartekvv4** [comment]
Dynamic System Report that's working fine: from dynpy.models.mechanics.motorcoach import DDOFTrolleySuspension 
DynSysOverviewReport(reported_object=DDOFTrolleySuspension ());

**Comment by bartekvv4** [comment]
Conducted team of 8: Kamil Jaśkielewicz, Anna Fila, Szymon Kozłowski, Magdalena Michalska, Marcel Kasprzak, Michał Kacperek, Piotr Loch, Bartosz Wanat

**Comment by bartekvv4** [comment]
Scheduled meeting on slack platform
