### ISSUE TITLE
Arrangement and execution of the meeting for implementation of `GitHubInterface` class that provides simple interface for `PyGitHub` library (issue #868 related)

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#870]
The goal is to arrange and execute the meeting for implementation of `GitHubInterface` class that provides simple interface for `PyGitHub` library. The following things should be prepared:

- [x] scope and schedule of meeting (in one week);

- [ ] conducting team (in two weeks);

- [x] guide or instructions with examples (one week before meeting);

- [ ] announcement (in Slack and Teams channel) with basic information (conducting persons, date,scope,schedule) (one week before meeting);

- [x] exemplary code in Jupyter (link) (one week before meeting).

**Comment by amvdek** [comment]
DONE
