### ISSUE TITLE
Arrangement and execution of the meeting for overview of reporting components from `utilites.components.guides` module (issue #884 related)

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#886]
The goal is to arrange and execute the meeting for overview of reporting components from `utilites.components.guides` module. The following things should be prepared:

- [x] scope and schedule of meeting (in one week);

- [x] conducting team (in two weeks);

- [x] guide or instructions with examples (one week before meeting);

- [x] announcement (in Slack and Teams channel) with basic information (conducting persons, date,scope,schedule) (one week before meeting);

- [x] exemplary code in Jupyter (link) (one week before meeting).

**Comment by MichauSzewczyk** [comment]
Arrangment has been executed - CW35/36
[link] - https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Micha%C5%82%20Szewczyk/00_PLAYGROPUND/2024-08-25-file-1.ipynb#id=2f5215
