### ISSUE TITLE
Implementation of `ModuleStructureComponent` class that creates a part of a report

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#912]
Class is to implement in `guide.en.py` module that creates a part (reporting component - formally child of `ReportComponent` class) of guide or report for reporting module.

**Comment by Danielstryjewski** [comment]
The code was checked with the following code:
```python
from dynpy.utilities.components.guides.en import ModuleStructureComponent

ModuleStructureComponent(None)
```
