### ISSUE TITLE
Implementation of `UsageOfMeetingCreatorComponent` class that creates a part of a report

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#918]
Class is to implement in `guide.en.py` module that creates a part (reporting component - formally child of `ReportComponent` class) of guide or report for `ReportComponent` class.

**Comment by lsikor** [comment]
The code was checked with the following code:

```python
from dynpy.utilities.components.guides.en import UsageOfMeetingCreatorComponent
UsageOfMeetingCreatorComponent(None)
```
