### ISSUE TITLE
A course of advanced modelling with Python

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#928]
Methods, functions or classes to implement are as follows:

- [x] #933

- [x] #934

- [x] #935 

- [x] #937

**Comment by bartekvv4** [comment]
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Bartosz%20Wanat/schedule/output/Harmonogram%20-%20Podstawy%20Pythona%20i%20zastosowania.pdf - Python basics schedule

https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Bartosz%20Wanat/schedule/output/Harmonogram%20-%20Zaawansowane%20modelowanie%20w%20języku%20Python.pdf - Advanced modelling schedule

**Comment by bartekvv4** [comment]
https://cocalc.com/projects/b51ce971-5b39-4911-ad97-ef59f15f0039/files/Useful%20guides/ - courses' guides

**Comment by bartekvv4** [comment]
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Szymon%20Kozłowski/Advanced%20modeling/advanced_modeling_concept.ipynb
The code is to be checked with the following call:

```python
SkibidiAdvancedModellingIssueGenerator2000inator();
```
Name is tbd and some things ought to be changed in code

**Comment by bartekvv4** [comment]
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Bartosz%20Wanat/schedule/schedule.ipynb#id=a317aa

**Comment by bogumilchilinski** [comment]
All subissues are done.
