### ISSUE TITLE
Implementation of `PythonBasicsScheduleComponent` class that creates a part of a report

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#929]
Class is to implement in `guide.development.en.py` module that creates a part (reporting component - formally child of `ReportComponent` class) of guide or report. It includes guides-classes matching (by classes name) and exemplary topics of reports.

**Comment by kjaskiel** [comment]
The code was checked with the following call:

```python
from dynpy.utilities.components.guides.development.en import PythonBasicsScheduleComponent
PythonBasicsScheduleComponent(None)
```
