### ISSUE TITLE
Implementation of `PythonBasicsGuidelinesComponent` class that creates a part of a report

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#931]
Class is to implement in `guide.development.en.py` module that creates a part (reporting component - formally child of `ReportComponent` class) of guide or report. The component includes information about schedule of meetings, form of issues, fixing guides with tutor during classes or preliminary presentation.

**Comment by kjaskiel** [comment]
Additional reporting component has been implemented (#933).

The code was checked with the following call:

```python
from dynpy.utilities.documents.document import PythonBasicsGuidelinesComponent
PythonBasicsGuidelinesComponent()
```
