### ISSUE TITLE
Implementation of `ModellingInPythonScheduleComponent` class that creates a part of a report

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#933]
Class is to implement in `guide.development.en.py` module that creates a part (reporting component - formally child of `ReportComponent` class) of guide or report. It includes schedule of weekly huddles conducted by selected participants, information of regular update of project progress, guides-classes matching (by classes name), exemplary topics of reports and meetings name template.

**Comment by kjaskiel** [comment]
Additional reporting component has been implemented (#933).

The code was checked with the following call:

```python
from dynpy.utilities.documents.document import ModellingInPythonScheduleComponent
ModellingInPythonScheduleComponent()
```
