### ISSUE TITLE
Development of car.py module

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#95]
Examine the module and its classes. Enhance the classes by employing inheritance to condense the code. Ensure that all classes are categorized into either the FINISHED or TODO group.

- [x] #350 

- [x] #351 

- [x] #352

**Comment by szymonkozlowski080** [comment]
https://cocalc.com/projects/f5eacfa1-ad37-41af-beea-da7216cf5881/files/Sandbox/Szymon%20Koz%C5%82owski/Tasks/carpy_dev.ipynb

Module examination

**Comment by szymonkozlowski080** [comment]
'''

dyn_sys = CarMovementPIDAdjust()
display(dyn_sys._eoms)
# display(dyn_sys.symbols_description())

param_dict = dyn_sys.get_numerical_parameters()
display(param_dict)

num_sys = dyn_sys.subs(param_dict).subs({dyn_sys.v_ref:30}).numerized()
sym_sys = num_sys.compute_solution(t_span,[0.0,0.0])

sym_sys[diff(dyn_sys.x,dyn_sys.ivar)].plot()

'''
