### ISSUE TITLE
Implementation of `StateOfTheArtReport` class that inherits by `Guide` document

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dynpy#972]
Class in `documents.document.py` is to be implemented.

**Comment by bartekvv4** [comment]
The code was checked with the following call:

from dynpy.utilities.documents.document import StateOfTheArtReport
StateOfTheArtReport()

**Comment by bartekvv4** [comment]
The code was checked with the following call:
```{python}
from dynpy.utilities.documents.document import StateOfTheArtReport
StateOfTheArtReport()
```
